# Generated by Django 3.0.2 on 2020-07-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_commentsection_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsection',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='use this format:yyyy-mm-dd', null=True),
        ),
    ]
