# Generated by Django 3.0.2 on 2020-07-22 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200720_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
