# Generated by Django 3.0.2 on 2020-07-22 02:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200722_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='c_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
